//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFormRight
    {
        public int AppFormRightsId { get; set; }
        public Nullable<int> AppFormId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Creator { get; set; }
        public Nullable<bool> Updater { get; set; }
        public Nullable<bool> Deleter { get; set; }
        public Nullable<bool> Viewer { get; set; }
        public Nullable<bool> Approver { get; set; }
        public Nullable<bool> Verifier { get; set; }
    
        public virtual AppForm AppForm { get; set; }
        public virtual User User { get; set; }
    }
}
