//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IGP()
        {
            this.IGPDetails = new HashSet<IGPDetail>();
        }
    
        public int IGPId { get; set; }
        public string IGPNumber { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> SupplierBillId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string VoucherNumber { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> VerfiedBy { get; set; }
        public Nullable<System.DateTime> VerfiedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual SupplierBill SupplierBill { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IGPDetail> IGPDetails { get; set; }
    }
}
