//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGPDetail
    {
        public int IGPDetailId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> IGPId { get; set; }
        public Nullable<int> SrNumber { get; set; }
        public string SRVNumber { get; set; }
        public Nullable<int> QuantityAccepted { get; set; }
        public Nullable<int> SRVCreatedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string BatchNumber { get; set; }
    
        public virtual IGP IGP { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
