//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierBill()
        {
            this.IGPs = new HashSet<IGP>();
            this.SupplierBillDeatils = new HashSet<SupplierBillDeatil>();
        }
    
        public int SupplierBillId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
        public Nullable<int> SalesTax { get; set; }
        public Nullable<int> SalesTaxTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IGP> IGPs { get; set; }
        public virtual PercentageValue PercentageValue { get; set; }
        public virtual PercentageValue PercentageValue1 { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierBillDeatil> SupplierBillDeatils { get; set; }
    }
}
