//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBillDeatil
    {
        public int SupplierBillDeatilId { get; set; }
        public Nullable<int> SupplierBillId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SupplierBill SupplierBill { get; set; }
    }
}
